### ISSUE TITLE
Should "Math.ceil" be used instead of "Math.floor"?

### ISSUE THREAD

**Issue by AsakuraMizu** [Cytoid/api.cytoid.io#8]
https://github.com/Cytoid/api.cytoid.io/blob/bc14add31056507e49ffa0fe9476e38caabf6b28/src/controllers/levels.ts#L364

I find this when I open [https://api.cytoid.io/levels?page=0](https://api.cytoid.io/levels?page=0) as well as [https://api.cytoid.io/levels?page=97](https://api.cytoid.io/levels?page=97) :thinking:

**Comment by PixelDust22** [comment]
Thanks! it is now fixed
